# Generated by Django 3.1.7 on 2021-04-02 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubScope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('scope', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interview.scope')),
            ],
            options={
                'verbose_name': 'Подраздел сферы',
                'verbose_name_plural': 'Подразделы сферы',
                'db_table': 'subscope',
            },
        ),
        migrations.AddField(
            model_name='questions',
            name='subscope',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='interview.subscope', verbose_name='Подраздел'),
            preserve_default=False,
        ),
    ]
