# Generated by Django 3.1.7 on 2021-04-07 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0002_auto_20210402_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profession',
            name='subscope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='interview.subscope'),
        ),
    ]
