# Generated by Django 3.1.7 on 2021-04-07 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_auto_20210407_1225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profession',
            name='subscope',
        ),
        migrations.AddField(
            model_name='profession',
            name='scope',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='interview.scope'),
            preserve_default=False,
        ),
    ]
