# Generated by Django 3.1.7 on 2021-06-05 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_profession_english_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionSalaries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parse_date', models.DateField(auto_now_add=True, verbose_name='Дата сбора информации')),
                ('low_salary', models.IntegerField(null=True, verbose_name='Нижняя вилка')),
                ('high_salary', models.IntegerField(null=True, verbose_name='Верхняя вилка')),
                ('region', models.CharField(choices=[('1', 'Москва'), ('113', 'Россия')], max_length=64, verbose_name='Регион')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.profession')),
            ],
            options={
                'verbose_name': 'Зарплата профессии',
                'verbose_name_plural': 'Зарплаты профессий',
                'db_table': 'professions_salaries',
            },
        ),
        migrations.CreateModel(
            name='ProfessionLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courses', models.URLField(null=True, verbose_name='Курсы')),
                ('vacancies', models.URLField(null=True, verbose_name='Вакансии')),
                ('profession', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.profession')),
            ],
            options={
                'verbose_name': 'Ссылки профессии',
                'verbose_name_plural': 'Ссылки профессий',
                'db_table': 'professions_links',
            },
        ),
    ]
