# Generated by Django 3.1.7 on 2021-06-05 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_professionlinks_professionsalaries'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Текст вопроса')),
                ('answer', models.TextField(verbose_name='Текст ответа')),
                ('scope', models.CharField(max_length=256, verbose_name='Сфера деятельности')),
                ('subscope', models.CharField(max_length=256, verbose_name='Подраздел сферы деятельности')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Вопросы', to='interview.account')),
            ],
            options={
                'verbose_name': 'Предложенный вопрос',
                'verbose_name_plural': 'Предложенные вопросы',
                'db_table': 'suggested_questions',
            },
        ),
    ]
