# Generated by Django 3.1.7 on 2021-06-06 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_suggestedquestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedquestions',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Вопросы', to='interview.account'),
        ),
    ]
