# Generated by Django 3.1.7 on 2021-06-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_auto_20210606_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='has_professions',
            field=models.BooleanField(default=True, verbose_name='Имеет профессии'),
        ),
    ]
