# Generated by Django 3.1.7 on 2021-06-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0011_scope_has_professions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedquestions',
            name='scope',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Сфера деятельности'),
        ),
        migrations.AlterField(
            model_name='suggestedquestions',
            name='subscope',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Подраздел сферы деятельности'),
        ),
    ]
