# Generated by Django 3.1.7 on 2021-06-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0013_auto_20210619_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='profession',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
