# Generated by Django 3.1.7 on 2021-06-22 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0014_profession_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionlinks',
            name='courses',
            field=models.URLField(blank=True, null=True, verbose_name='Курсы'),
        ),
        migrations.AlterField(
            model_name='professionlinks',
            name='vacancies',
            field=models.URLField(blank=True, null=True, verbose_name='Вакансии'),
        ),
    ]
