# Generated by Django 3.1.7 on 2021-06-22 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0016_auto_20210622_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
