# Generated by Django 3.1.7 on 2021-06-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0017_auto_20210622_0331'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
