# Generated by Django 3.1.7 on 2021-06-23 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0019_auto_20210622_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Страна'),
        ),
    ]
