# Generated by Django 3.1.7 on 2021-07-07 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0020_auto_20210623_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Заголовок')),
                ('status', models.CharField(choices=[('Created', 'Создан'), ('Moderation', 'На модерации'), ('Published', 'Опубликован'), ('Declined', 'Отказано в публикации')], default='Created', max_length=32, verbose_name='Статус')),
                ('additional_info', models.TextField(null=True, verbose_name='Информация от администратора/модератора')),
                ('body', models.TextField(verbose_name='Текст поста')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='interview.account')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'db_table': 'posts',
            },
        ),
        migrations.CreateModel(
            name='PostComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Комментарий')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.account')),
            ],
            options={
                'verbose_name': 'Комментарий поста',
                'verbose_name_plural': 'Комментарии поста',
                'db_table': 'post_comments',
            },
        ),
        migrations.CreateModel(
            name='NotifyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_text', models.TextField(verbose_name='Комментарий')),
                ('is_read', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.account')),
            ],
            options={
                'verbose_name': 'Уведомление пользователя',
                'verbose_name_plural': 'Уведомления пользователя',
                'db_table': 'user_notifications',
            },
        ),
        migrations.CreateModel(
            name='PostLikes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview.account')),
            ],
            options={
                'verbose_name': 'Лайк поста',
                'verbose_name_plural': 'Лайки поста',
                'db_table': 'post_likes',
                'unique_together': {('post_id', 'user_id')},
            },
        ),
    ]
