# Generated by Django 3.1.7 on 2021-07-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0021_notifyuser_post_postcomments_postlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='additional_info',
            field=models.TextField(blank=True, null=True, verbose_name='Информация от администратора/модератора'),
        ),
    ]
