# Generated by Django 3.1.7 on 2021-09-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0022_auto_20210714_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='has_questions',
            field=models.BooleanField(default=True, verbose_name='Имеет вопросы'),
        ),
    ]
