# Generated by Django 3.1.7 on 2021-12-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0026_auto_20211123_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscope',
            name='icon',
            field=models.CharField(max_length=32, null=True, verbose_name='Название иконки'),
        ),
    ]
